//= include.js
var gulp = require('gulp'),
    mainBowerFiles = require('main-bower-files'),
    watch = require('gulp-watch'),
    prefixer = require('gulp-autoprefixer'),
    uglify = require('gulp-uglify'),
    sourcemaps = require('gulp-sourcemaps'),
    sass = require('gulp-sass'),
    cleanCSS = require('gulp-clean-css'),
    imagemin = require('gulp-imagemin'),
    pngquant = require('imagemin-pngquant'),
    rimraf = require('rimraf'),
    browserSync = require("browser-sync").create(),
    newer = require("gulp-newer"),//сличает даты обновления файлов, если такой же файл уже есть
    rev = require("gulp-rev"),//подсчитывает хеш файла и добавляет его в имя: main-abcdfg.css for long term cashing
    revReplace = require("gulp-rev-replace"),//прописывает файл стилей или яваскрипта в html
    rigger = require('gulp-rigger'),
    reload = browserSync.reload;